import type { SchemaType } from '../types';

export const productSchema: SchemaType = {
  name: 'product',
  title: 'Product',
  type: 'document',
  fields: [
    { name: 'title', title: 'Title', type: 'string', required: true },
    { name: 'slug', title: 'Slug', type: 'slug', required: true },
    { name: 'sku', title: 'SKU', type: 'string' },
    { name: 'summary', title: 'Summary', type: 'text' },
    { name: 'description', title: 'Description', type: 'text' },
    { name: 'badge', title: 'Badge label', type: 'string' },
    { name: 'price', title: 'Price', type: 'number' },
    { name: 'compareAtPrice', title: 'Compare at price', type: 'number' },
    { name: 'priceLabel', title: 'Price label', type: 'string' },
    { name: 'currency', title: 'Currency', type: 'string' },
    { name: 'inStock', title: 'In stock', type: 'boolean' },
    { name: 'featured', title: 'Featured', type: 'boolean' },
    { name: 'ratingAverage', title: 'Average rating', type: 'number' },
    { name: 'ratingCount', title: 'Rating count', type: 'number' },
    {
      name: 'collections',
      title: 'Collections',
      type: 'array',
      of: ['string'],
    },
    {
      name: 'topFinishes',
      title: 'Top finishes',
      type: 'array',
      of: ['string'],
    },
    {
      name: 'colors',
      title: 'Colors',
      type: 'array',
      of: ['string'],
    },
    {
      name: 'sizes',
      title: 'Sizes',
      type: 'array',
      of: ['string'],
    },
    {
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: ['category'],
    },
    { name: 'heroImage', title: 'Hero image', type: 'image' },
    {
      name: 'images',
      title: 'Images',
      type: 'array',
      of: ['image'],
    },
    { name: 'roomSceneImage', title: 'Room scene image', type: 'image' },
    { name: 'dimensions', title: 'Dimensions', type: 'text' },
    { name: 'assemblyAndCare', title: 'Assembly and care', type: 'text' },
    { name: 'shippingAndReturns', title: 'Shipping and returns', type: 'text' },
    {
      name: 'whyYouWillLoveIt',
      title: 'Why you will love it',
      type: 'array',
      of: ['string'],
    },
    {
      name: 'guarantees',
      title: 'Guarantees',
      type: 'array',
      of: ['string'],
    },
    {
      name: 'body',
      title: 'Body',
      type: 'array',
      of: ['block', 'image'],
    },
    { name: 'seo', title: 'SEO', type: 'seo' },
  ],
};
